### ISSUE TITLE
Title hidden on different fonts

### ISSUE THREAD

**Issue by aditya-singh9** [aditya-singh9/notem#38]
make font sizes according to the fonts.
on the notes section too, their is big fonts which leads to less content in one board.

![image](https://user-images.githubusercontent.com/76763565/194325294-5a4f268e-76fa-4845-859e-93e140c7c4e4.png)

**Comment by NalinPlad** [comment]
this issue is due to the "pixel" font being different from all the other ones, all of the fonts have the same font-size, the "pixel" font is just literally smaller for some reason. If you want to fix this I suggest fixing the pixel font so its not so small and then just setting the font size for everything smaller

**Comment by aditya-singh9** [comment]
Would you like to solve this bug.

**Comment by cjlovelace** [comment]
https://github.com/aditya-singh9/notem/pull/40

Changes addressed here for reference. :)
